### ISSUE TITLE
Le service scrumblr ne démarre pas

### ISSUE THREAD

**Issue by hidrarga** [YunoHost-Apps/scrumblr_ynh#10]
Après l'installation, le service scrumblr ne démarre pas.

Après inspection dans les logs, j'ai découvert que le problème se situait dans le fichier `/etc/systemd/system/scrumblr.service`. Il faut remplacer la ligne
```
ExecStart=/opt/node_n/n/versions/node/6.2.0/bin server.js --port 4000
```
par
```
ExecStart=/opt/node_n/n/versions/node/6.2.0/bin/node server.js --port 4000
```

Serait-il possible de modifier le script d'installation en conséquence ? Merci :slightly_smiling_face:

**Comment by frju365** [comment]
I did it. I didn't try the app (not time yet).
