### ISSUE TITLE
Problème installation Scrumblr Debian 10

### ISSUE THREAD

**Issue by rooooose** [YunoHost-Apps/scrumblr_ynh#14]
Bonjour,
j'essaie d'installer Scrumblr sur la version 10 Debian. Mais je n'y parviens pas.
Lorsqu'on veut finir l'install, il y a une erreur comme quoi il manque une dépendance, mais qu'on ne peut pas installer. Avez-vous testé avec la dernière version ? 
J'ai tenté l'installation avec plusieurs docs, notamment celle de Framasoft (https://framacloud.org/fr/cultiver-son-jardin/scrumblr.html) et l'erreur est toujours la même.

(PROD:root@lamp2020)/dataweb/scrumblr (master) $ cat /etc/debian_version
10.4
(PROD:root@lamp2020)/dataweb/scrumblr (master) $ uname -a
Linux lamp2020 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

(PROD:root@lamp2020)/dataweb/scrumblr (master) $ npm -version
5.8.0

(PROD:root@lamp2020)/dataweb/scrumblr (master) $ node --version
v10.19.0

(PROD:root@lamp2020)/dataweb/scrumblr (master) $ systemctl enable --now redis-server.service
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
(PROD:root@lamp2020)/dataweb/scrumblr (master) $ systemctl status redis-server.service
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-05-18 14:13:29 UTC; 1min 29s ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
 Main PID: 11088 (redis-server)
    Tasks: 4 (limit: 4915)
   Memory: 8.8M
   CGroup: /system.slice/redis-server.service
           └─11088 /usr/bin/redis-server 127.0.0.1:6379

mai 18 14:13:29 lamp2020 systemd[1]: Starting Advanced key-value store...
mai 18 14:13:29 lamp2020 systemd[1]: redis-server.service: Can't open PID file /run/redis/redis-server.pid (yet?) after start: No such file or directory
mai 18 14:13:29 lamp2020 systemd[1]: Started Advanced key-value store.

(PROD:root@lamp2020)/dataweb/scrumblr (master) $ npm install
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated jade@1.5.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN notice [SECURITY] constantinople has the following vulnerability: 1 critical. Go here for more details: https://www.npmjs.com/advisories?search=constantinople&version=2.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated constantinople@2.0.1: Please update to at least constantinople 3.1.1
npm WARN notice [SECURITY] uglify-js has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=uglify-js&version=2.4.24 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] uglify-js has the following vulnerabilities: 2 low. Go here for more details: https://www.npmjs.com/advisories?search=uglify-js&version=2.2.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN rollback Rolling back jade@1.5.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/dataweb/scrumblr/node_modules/jade/package.json.628375101'
npm WARN rollback Rolling back socket.io@1.7.4 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/dataweb/scrumblr/node_modules/socket.io/package.json.4062228009'
npm WARN rollback Rolling back transformers@2.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/dataweb/scrumblr/node_modules/jade/node_modules/transformers/package.json.405454580'
npm WARN rollback Rolling back optimist@0.3.7 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/dataweb/scrumblr/node_modules/jade/node_modules/optimist/package.json.849869484'
npm ERR! path /dataweb/scrumblr/node_modules/socket.io/node_modules/ms/package.json.107341474
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
**npm ERR! enoent ENOENT: no such file or directory, open '/dataweb/scrumblr/node_modules/socket.io/node_modules/ms/package.json.107341474'**
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-18T14_16_44_095Z-debug.log
(PROD:root@lamp2020)/dataweb/scrumblr (master) $

Merci beaucoup pour votre aide !

**Comment by ericgaspar** [comment]
Closing. New version available in master.
