### ISSUE TITLE
Use Framemo (or another fork) instead of Scrumblr ?

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/scrumblr_ynh#4]
As you can see on https://github.com/aliasaria/scrumblr/pulls, it seems that the development of Scrumblr is stucked.

New fonctionnalities aren't on it, and some security issues have not been fixed.

Solution: use a fork as source.

**Comment by frju365** [comment]
Fixed with PR https://github.com/YunoHost-Apps/scrumblr_ynh/pull/5
